### Imports & Definitions

In [1]:
import sys
sys.path.append("../../utils")
from definitions import *

### Read results

In [2]:
df = pd.read_csv(ARTIFACTS_DIR_PATH.joinpath("metrics/knowledge_tests/obrazovaka_full_results.csv"))

In [5]:
llama2 = df[df["model"] == "llama2"]
llama2["percent"].mean()

23.239333333333335

In [8]:
llama3 = df[df["model"] == "llama3"]
llama3["percent"].mean()

38.707333333333324

In [11]:
df = pd.read_csv(ARTIFACTS_DIR_PATH.joinpath("junk/some_results_stupid.csv"))
df

,Unnamed: 0,model,test_path,num_ok,num_all,percent
0,0,llama2,../../metrics/knowledge_tests/obrazovaka/the_d...,4,16,25.00
1,1,llama2,../../metrics/knowledge_tests/obrazovaka/the_b...,3,10,30.00
2,2,llama2,../../metrics/knowledge_tests/obrazovaka/and_q...,4,18,22.22
3,3,llama2,../../metrics/knowledge_tests/obrazovaka/oblom...,2,19,10.53
4,4,llama2,../../metrics/knowledge_tests/obrazovaka/eveni...,2,10,20.00
5,5,llama2,../../metrics/knowledge_tests/obrazovaka/docto...,3,13,23.08
6,6,llama2,../../metrics/knowledge_tests/obrazovaka/war_a...,16,70,22.86
7,7,llama2,../../metrics/knowledge_tests/obrazovaka/the_m...,5,16,31.25
8,8,llama2,../../metrics/knowledge_tests/obrazovaka/dead_...,7,19,36.84
9,9,llama2,../../metrics/knowledge_tests/obrazovaka/the_g...,1,10,10.00
10,10,llama2,../../metrics/knowledge_tests/obrazovaka/the_w...,2,10,20.00
11,11,llama2,../../metrics/knowledge_tests/obrazovaka/the_h...,5,30,16.67
12,12,llama2,../../metrics/knowledge_tests/obrazovaka/idiot...,3,12,25.00
13,13,llama2,../../metrics/knowledge_tests/obrazovaka/crime...,5,16,31.25
14,14,llama2,../../metrics/knowledge_tests/obrazovaka/anna_...,3,10,30.00
15,15,llama3,../../metrics/knowledge_tests/obrazovaka/the_d...,5,16,31.25
16,16,llama3,../../metrics/knowledge_tests/obrazovaka/the_b...,3,10,30.00
17,17,llama3,../../metrics/knowledge_tests/obrazovaka/and_q...,8,18,44.44
18,18,llama3,../../metrics/knowledge_tests/obrazovaka/oblom...,10,19,52.63
19,19,llama3,../../metrics/knowledge_tests/obrazovaka/eveni...,0,10,0.00
20,20,llama3,../../metrics/knowledge_tests/obrazovaka/docto...,6,13,46.15
21,21,llama3,../../metrics/knowledge_tests/obrazovaka/war_a...,23,70,32.86
22,22,llama3,../../metrics/knowledge_tests/obrazovaka/the_m...,4,16,25.00
23,23,llama3,../../metrics/knowledge_tests/obrazovaka/dead_...,4,19,21.05
24,24,llama3,../../metrics/knowledge_tests/obrazovaka/the_g...,5,10,50.00
25,25,llama3,../../metrics/knowledge_tests/obrazovaka/the_w...,2,10,20.00
26,26,llama3,../../metrics/knowledge_tests/obrazovaka/the_h...,13,30,43.33
27,27,llama3,../../metrics/knowledge_tests/obrazovaka/idiot...,3,12,25.00
28,28,llama3,../../metrics/knowledge_tests/obrazovaka/crime...,7,16,43.75
29,29,llama3,../../metrics/knowledge_tests/obrazovaka/anna_...,4,10,40.00

In [10]:
llama2 = df[df["model"] == "llama2"]
llama2["percent"].mean()

23.646666666666665

In [12]:
llama3 = df[df["model"] == "llama3"]
llama3["percent"].mean()

33.69733333333333

In [13]:
df = pd.read_csv(ARTIFACTS_DIR_PATH.joinpath("junk/some_results_briefly.csv"))
df

,Unnamed: 0,model,test_path,num_ok,num_all,percent
0,0,llama2,../../metrics/knowledge_tests/obrazovaka/the_d...,4,16,25.00
1,1,llama2,../../metrics/knowledge_tests/obrazovaka/the_b...,1,10,10.00
2,2,llama2,../../metrics/knowledge_tests/obrazovaka/and_q...,3,18,16.67
3,3,llama2,../../metrics/knowledge_tests/obrazovaka/oblom...,2,19,10.53
4,4,llama2,../../metrics/knowledge_tests/obrazovaka/eveni...,2,10,20.00
5,5,llama2,../../metrics/knowledge_tests/obrazovaka/docto...,2,13,15.38
6,6,llama2,../../metrics/knowledge_tests/obrazovaka/war_a...,14,70,20.00
7,7,llama2,../../metrics/knowledge_tests/obrazovaka/the_m...,4,16,25.00
8,8,llama2,../../metrics/knowledge_tests/obrazovaka/dead_...,3,19,15.79
9,9,llama2,../../metrics/knowledge_tests/obrazovaka/the_g...,2,10,20.00
10,10,llama2,../../metrics/knowledge_tests/obrazovaka/the_w...,3,10,30.00
11,11,llama2,../../metrics/knowledge_tests/obrazovaka/the_h...,6,30,20.00
12,12,llama2,../../metrics/knowledge_tests/obrazovaka/idiot...,3,12,25.00
13,13,llama2,../../metrics/knowledge_tests/obrazovaka/crime...,3,16,18.75
14,14,llama2,../../metrics/knowledge_tests/obrazovaka/anna_...,2,10,20.00
15,15,llama3,../../metrics/knowledge_tests/obrazovaka/the_d...,8,16,50.00
16,16,llama3,../../metrics/knowledge_tests/obrazovaka/the_b...,7,10,70.00
17,17,llama3,../../metrics/knowledge_tests/obrazovaka/and_q...,11,18,61.11
18,18,llama3,../../metrics/knowledge_tests/obrazovaka/oblom...,14,19,73.68
19,19,llama3,../../metrics/knowledge_tests/obrazovaka/eveni...,1,10,10.00
20,20,llama3,../../metrics/knowledge_tests/obrazovaka/docto...,7,13,53.85
21,21,llama3,../../metrics/knowledge_tests/obrazovaka/war_a...,34,70,48.57
22,22,llama3,../../metrics/knowledge_tests/obrazovaka/the_m...,10,16,62.50
23,23,llama3,../../metrics/knowledge_tests/obrazovaka/dead_...,10,19,52.63
24,24,llama3,../../metrics/knowledge_tests/obrazovaka/the_g...,6,10,60.00
25,25,llama3,../../metrics/knowledge_tests/obrazovaka/the_w...,6,10,60.00
26,26,llama3,../../metrics/knowledge_tests/obrazovaka/the_h...,11,30,36.67
27,27,llama3,../../metrics/knowledge_tests/obrazovaka/idiot...,6,12,50.00
28,28,llama3,../../metrics/knowledge_tests/obrazovaka/crime...,10,16,62.50
29,29,llama3,../../metrics/knowledge_tests/obrazovaka/anna_...,5,10,50.00

In [14]:
llama2 = df[df["model"] == "llama2"]
llama2["percent"].mean()

19.474666666666668

In [15]:
llama3 = df[df["model"] == "llama3"]
llama3["percent"].mean()

53.434